package syncro.org;
class syncstatic{
	 synchronized static public void generate(String threadcode) {
		for(int i=1;i<=10;i++) {
			if(i<=5) {
				System.out.print("[");
			}
			else {
				System.out.print("]");
			}
		}
		System.out.println("Generated by: "+threadcode);
	}
}
public class Static {
	public static void main(String[] args) {
//		syncstatic sy1=new syncstatic();
//		syncstatic sy2=new syncstatic();
		new Thread(new Runnable(){
			public void run() {
				for(int i=1;i<=5;i++) {
					syncstatic.generate("thread 1");
					}
				}
		}).start();
		new Thread(new Runnable(){
			public void run() {
				for(int i=1;i<=5;i++) {
					syncstatic.generate("thread 2");
					}
				}
		}).start();
	}
}

